name: Build Model

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    # if: "!contains(github.event.head_commit.message, 'NO_AB')"

    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
      EXPERIMENT_NAME: ${{vars.EXPERIMENT_NAME}}
      MLFLOW_URL: ${{vars.MLFLOW_URI}}
      MODEL_NAME: ${{vars.MODEL_NAME}}
    steps:      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Train and save model
        run: |
          python src/main.py
          
      - name: Run model tests
        run: python model_tests/test_model.py

      - name: Register model in MLflow
        run: python scripts/register_model.py
